sudo: false
language: scala

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - sbt -sbt-version 0.13.7 ++$TRAVIS_SCALA_VERSION coverage test

after_success:
  - sbt coveralls

